### PR TITLE
[WIP] Update to Latest tpsdk

### PR DESCRIPTION
**Pull request by gfritz**
Opening for help with #26

### CODE REVIEW

**Comment by dsyme** [comment]
Test failures - I haven't looked into them
```
[00:01:38] Tests run: 21, Errors: 0, Failures: 7, Inconclusive: 0, Time: 19.4431047 seconds
[00:01:38]   Not run: 0, Invalid: 0, Ignored: 0, Skipped: 0
[00:01:38] 
[00:01:38] Errors and Failures:
[00:01:38] 1) Test Failure : FSharp.Data.TypeProviders.Tests.EdmxFile.EDMX Tests 1
[00:01:38]    ... FAILURE: expected 1, got 2  
[00:01:38] at FSharp.Data.TypeProviders.Tests.EdmxFile.Infrastructure.check[a](String s, a v1, a v2) in C:\projects\fsharp-data-typeproviders\tests\FSharp.Data.TypeProviders.Tests\EdmxFile\EdmxFileTests.fs:line 17
[00:01:38] at FSharp.Data.TypeProviders.Tests.EdmxFile.CheckEdmxfileTypeProvider.checkHostedType(Type hostedType) in C:\projects\fsharp-data-typeproviders\tests\FSharp.Data.TypeProviders.Tests\EdmxFile\EdmxFileTests.fs:line 32
[00:01:38] at FSharp.Data.TypeProviders.Tests.EdmxFile.CheckEdmxfileTypeProvider.instantiateTypeProviderAndCheckOneHostedType(String edmxfile, String[] typeFullPath) in C:\projects\fsharp-data-typeproviders\tests\FSharp.Data.TypeProviders.Tests\EdmxFile\EdmxFileTests.fs:line 109
[00:01:38] 
[00:01:38] 2) Test Failure : FSharp.Data.TypeProviders.Tests.EdmxFile.EDMX Tests 2
[00:01:38]    ... FAILURE: expected 1, got 2  
[00:01:38] at FSharp.Data.TypeProviders.Tests.EdmxFile.Infrastructure.check[a](String s, a v1, a v2) in C:\projects\fsharp-data-typeproviders\tests\FSharp.Data.TypeProviders.Tests\EdmxFile\EdmxFileTests.fs:line 17
[00:01:38] at FSharp.Data.TypeProviders.Tests.EdmxFile.CheckEdmxfileTypeProvider.checkHostedType(Type hostedType) in C:\projects\fsharp-data-typeproviders\tests\FSharp.Data.TypeProviders.Tests\EdmxFile\EdmxFileTests.fs:line 32
[00:01:38] at FSharp.Data.TypeProviders.Tests.EdmxFile.CheckEdmxfileTypeProvider.instantiateTypeProviderAndCheckOneHostedType(String edmxfile, String[] typeFullPath) in C:\projects\fsharp-data-typeproviders\tests\FSharp.Data.TypeProviders.Tests\EdmxFile\EdmxFileTests.fs:line 109
[00:01:38] 
[00:01:38] 3) Test Failure : FSharp.Data.TypeProviders.Tests.OdataServiceTests.OData Tests 1
[00:01:38]    test failed
[00:01:38] at FSharp.Data.TypeProviders.Tests.OdataServiceTests.instantiateTypeProviderAndCheckOneHostedType(FSharpOption`1 useLocalSchemaFile, FSharpOption`1 useForceUpdate, String[] typeFullPath) in C:\projects\fsharp-data-typeproviders\tests\FSharp.Data.TypeProviders.Tests\ODataService\ODataServiceTests.fs:line 114
[00:01:38] 
[00:01:38] 4) Test Failure : FSharp.Data.TypeProviders.Tests.OdataServiceTests.OData Tests 2
[00:01:38]    test failed
[00:01:38] at FSharp.Data.TypeProviders.Tests.OdataServiceTests.instantiateTypeProviderAndCheckOneHostedType(FSharpOption`1 useLocalSchemaFile, FSharpOption`1 useForceUpdate, String[] typeFullPath) in C:\projects\fsharp-data-typeproviders\tests\FSharp.Data.TypeProviders.Tests\ODataService\ODataServiceTests.fs:line 114
[00:01:38] at FSharp.Data.TypeProviders.Tests.OdataServiceTests.OData Tests 2() in C:\projects\fsharp-data-typeproviders\tests\FSharp.Data.TypeProviders.Tests\ODataService\ODataServiceTests.fs:line 126
[00:01:38] 
[00:01:38] 5) Test Failure : FSharp.Data.TypeProviders.Tests.OdataServiceTests.OData Tests 4
[00:01:38]    test failed
[00:01:38] at FSharp.Data.TypeProviders.Tests.OdataServiceTests.instantiateTypeProviderAndCheckOneHostedType(FSharpOption`1 useLocalSchemaFile, FSharpOption`1 useForceUpdate, String[] typeFullPath) in C:\projects\fsharp-data-typeproviders\tests\FSharp.Data.TypeProviders.Tests\ODataService\ODataServiceTests.fs:line 114
[00:01:38] at FSharp.Data.TypeProviders.Tests.OdataServiceTests.OData Tests 4() in C:\projects\fsharp-data-typeproviders\tests\FSharp.Data.TypeProviders.Tests\ODataService\ODataServiceTests.fs:line 139
[00:01:38] 
[00:01:38] 6) Test Failure : FSharp.Data.TypeProviders.Tests.WsdlServiceTests.WSDL Tests 1
[00:01:38]    ... FAILURE: expected 1, got 2  
[00:01:38] at FSharp.Data.TypeProviders.Tests.WsdlServiceTests.Infrastructure.check[a](String s, a v1, a v2) in C:\projects\fsharp-data-typeproviders\tests\FSharp.Data.TypeProviders.Tests\WsdlService\WsdlServiceTests.fs:line 17
[00:01:38] at FSharp.Data.TypeProviders.Tests.WsdlServiceTests.SimpleWsdlTest.CheckHostedType(Type hostedType) in C:\projects\fsharp-data-typeproviders\tests\FSharp.Data.TypeProviders.Tests\WsdlService\WsdlServiceTests.fs:line 141
[00:01:38] at FSharp.Data.TypeProviders.Tests.WsdlServiceTests.-ctor@125.Invoke(Type arg00) in C:\projects\fsharp-data-typeproviders\tests\FSharp.Data.TypeProviders.Tests\WsdlService\WsdlServiceTests.fs:line 125
[00:01:38] at FSharp.Data.TypeProviders.Tests.WsdlServiceTests.WsdlServiceTest.Run() in C:\projects\fsharp-data-typeproviders\tests\FSharp.Data.TypeProviders.Tests\WsdlService\WsdlServiceTests.fs:line 67
[00:01:38] 
[00:01:38] 7) Test Failure : FSharp.Data.TypeProviders.Tests.WsdlServiceTests.WSDL Tests 2
[00:01:38]    ... FAILURE: expected 1, got 2  
[00:01:38] at FSharp.Data.TypeProviders.Tests.WsdlServiceTests.Infrastructure.check[a](String s, a v1, a v2) in C:\projects\fsharp-data-typeproviders\tests\FSharp.Data.TypeProviders.Tests\WsdlService\WsdlServiceTests.fs:line 17
[00:01:38] at FSharp.Data.TypeProviders.Tests.WsdlServiceTests.XIgniteWsdlTest.CheckHostedType(Type hostedType) in C:\projects\fsharp-data-typeproviders\tests\FSharp.Data.TypeProviders.Tests\WsdlService\WsdlServiceTests.fs:line 178
[00:01:38] at FSharp.Data.TypeProviders.Tests.WsdlServiceTests.-ctor@162-1.Invoke(Type arg00) in C:\projects\fsharp-data-typeproviders\tests\FSharp.Data.TypeProviders.Tests\WsdlService\WsdlServiceTests.fs:line 162
[00:01:38] at FSharp.Data.TypeProviders.Tests.WsdlServiceTests.WsdlServiceTest.Run() in C:\projects\fsharp-data-typeproviders\tests\FSharp.Data.TypeProviders.Tests\WsdlService\WsdlServiceTests.fs:line 67
[00:01:38] 
```

**Comment by dsyme** [comment]
@gfritz @colinbull I updated this with fixes to make the tests pass (the latest TPSDK respects the BindingFlags paramaters being passed in more accurately).

@colinbull I also bumped the version to 5.1.0.0

**Comment by dsyme** [comment]
This needs quite a bit more work.  Among other things we have to switch to use TypeProviderForNamespaces

**Comment by dsyme** [comment]
I've updated this to use TypeProvidersForNamespaces

However, this set of type providers is particularly, deeply unusual in that it uses an enormous "hack" - it takes System.Type objects from one generated DLL (the one generated by the tool like `sqlmetal.exe`) and "rearranges them" to pretend to be nested types in a separate generated DLL  (the one generated using `ProvidedAssembly()`). This is completely unsupported in the new TPSDK and is a silly thing to be allowing, it was only ever allowed for this type provider in particular.  

I'm not sure quite what to do about this.  We could hack in some support for this into the TPSDK I suppose, just to get this TP back into shape.  Or else we could abandon attempts to get this TP updated to the latest TPSDK and just put it into maintenance-only mode (which is effectively what it's in anyway)

**Comment by colinbull** [comment]
I would definitely prefer not to special case the new SDK for this. Most of
the stuff backing these providers is dead or on its way out anyway. The
only one that is likely to last a while is the WSDL one, because well
“Enterprise”.

So I think I agree leave this in maintenance mode. But I think I should
probably have a look at solutions for WSDL in a new TP.

What do you think?

**Comment by gfritz** [comment]
Looking at the PR history I know I did not contribute a lot, but if I wouldn't get in the way too much, I would want to help make WSDL work in a new TP.

I use it in one production application at my company (our first and only project with F# in it). It would be cool if I could come back to my team and say the whole application could pivot to .Net Core, even if I can't do more than cheer from the sidelines or be a tester.

**Comment by thinkbeforecoding** [comment]
I noticed there is now a netcore version of svcutil:
https://www.nuget.org/packages/dotnet-svcutil

Would it be better to spawn a new project, or update this one ?

**Comment by colinbull** [comment]
IIRC I followed that when it was part of the WCF rewrite. I think there are
some significant differences, so it is probably better for a rewrite.

**Comment by gfritz** [comment]
To close the loop, there is this modern one by @thinkbeforecoding https://github.com/fsprojects/FSharp.Data.WsdlProvider that I have not finished testing for my scenario. It should be good enough to close out this issue.

**Pull request closed without merging**
